# Generated by Django 5.2.4 on 2025-07-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='FACE_AUTH_ENABLED',
            new_name='face_auth_enabled',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
