# Generated by Django 5.2.4 on 2025-07-22 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_clientapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('face_encoding', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_users', to='auth_api.clientapp')),
            ],
            options={
                'unique_together': {('app', 'email')},
            },
        ),
    ]
