# Generated by Django 5.2.4 on 2025-07-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_enduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
