# Generated by Django 4.2.23 on 2025-07-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_enduser_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientapp',
            name='strictness',
        ),
        migrations.AddField(
            model_name='clientapp',
            name='CONFIDENCE_THRESHOLD',
            field=models.FloatField(default=0.18),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='FALLBACK_THRESHOLD',
            field=models.FloatField(default=0.25),
        ),
    ]
