# Generated by Django 4.2.23 on 2025-07-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_remove_clientapp_strictness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_image', models.ImageField(upload_to='enduser_feedback_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feedback_type', models.CharField(blank=True, max_length=50)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enduser_feedback', to='auth_api.clientapp')),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_images', to='auth_api.enduser')),
            ],
            options={
                'verbose_name': 'Feedback de Usuario Final',
                'verbose_name_plural': 'Feedbacks de Usuarios Finales',
                'ordering': ['-timestamp'],
            },
        ),
    ]
