# Generated by Django 4.2.23 on 2025-07-27 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0008_enduserfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('submitted_image', models.ImageField(blank=True, null=True, upload_to='login_attempts_images/')),
                ('best_match_distance', models.FloatField(blank=True, null=True)),
                ('initial_status', models.CharField(choices=[('success', 'Éxito (alta confianza)'), ('ambiguous_match', 'Coincidencia ambigua'), ('no_match', 'Sin coincidencia'), ('error', 'Error de procesamiento')], max_length=20)),
                ('is_verified_and_correct', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to='auth_api.clientapp')),
                ('attempting_end_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts_as_attempting', to='auth_api.enduser')),
                ('best_match_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts_as_best_match', to='auth_api.enduser')),
                ('confirmed_by_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts_confirmed', to='auth_api.enduser')),
            ],
            options={
                'verbose_name': 'Intento de Login de Usuario Final',
                'verbose_name_plural': 'Intentos de Login de Usuarios Finales',
                'ordering': ['-timestamp'],
            },
        ),
    ]
