# Generated by Django 4.2.23 on 2025-07-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_enduserloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduserloginattempt',
            name='user_feedback',
            field=models.CharField(blank=True, choices=[('correcto', 'Correcto'), ('incorrecto', 'Incorrecto')], help_text='Feedback directo del usuario sobre el intento de login.', max_length=10, null=True),
        ),
    ]
