# Generated by Django 4.2.23 on 2025-07-27 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0010_enduserloginattempt_user_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('submitted_image', models.ImageField(blank=True, null=True, upload_to='customuser_login_attempts_images/')),
                ('best_match_distance', models.FloatField(blank=True, null=True)),
                ('initial_status', models.CharField(choices=[('success', 'Éxito (alta confianza)'), ('ambiguous_match', 'Coincidencia ambigua'), ('no_match', 'Sin coincidencia'), ('error', 'Error de procesamiento')], max_length=20)),
                ('user_feedback', models.CharField(blank=True, choices=[('correcto', 'Correcto'), ('incorrecto', 'Incorrecto')], help_text='Feedback directo del usuario sobre el intento de login.', max_length=10, null=True)),
                ('is_verified_and_correct', models.BooleanField(default=False)),
                ('best_match_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts_as_best_match_customuser', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts_confirmed_customuser', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de Login de Usuario del Sistema',
                'verbose_name_plural': 'Intentos de Login de Usuarios del Sistema',
                'ordering': ['-timestamp'],
            },
        ),
    ]
