# Generated by Django 4.2.23 on 2025-07-27 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_customuserloginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserloginattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
