# Generated by Django 5.2.4 on 2025-07-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facial_auth_app', '0002_alter_facialrecognitionprofile_face_encoding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facialloginattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClientApp',
        ),
        migrations.DeleteModel(
            name='FacialLoginAttempt',
        ),
    ]
