# Generated by Django 4.2.23 on 2025-07-26 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facial_auth_app', '0003_remove_facialloginattempt_user_delete_clientapp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facialrecognitionprofile',
            options={'verbose_name': 'Facial Recognition Profile', 'verbose_name_plural': 'Facial Recognition Profiles'},
        ),
        migrations.AddField(
            model_name='facialrecognitionprofile',
            name='description',
            field=models.CharField(default='Initial registration', max_length=255),
        ),
        migrations.AlterField(
            model_name='facialrecognitionprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facial_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FaceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_image', models.ImageField(upload_to='face_feedback_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
